version: '3.8'
services:
  price-app:
    image: agabaembedded/price-prediction:latest
    ports:
      - "8000:8000"
    env_file:
      - .env  # This automatically looks for a file named .env in the same folder
    restart: always