stages:
  fetch_data:
    cmd: python fetch/fetch_data.py
    deps:
      - fetch/fetch_data.py
      - configs/config.yaml
    outs:
      - data/fetch
      
  feature_engineering:
    cmd: python features/feature_engineering.py
    deps:
      - features/feature_engineering.py
      - data/fetch
      - configs/config.yaml
    outs:
      - data/features
      
  final_training:
    cmd: python training/train_final.py
    deps:
      - training/train_final.py
      - data/features
      - configs/config.yaml
    outs:
      - saved_models
      

    