name: Daily Signal Prediction
on:
  schedule:
    # 00:00 UTC
    - cron: '32 0 * * *'
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r pred_requirements.txt

      - name: Run Prediction
        env:
          
          DAGSHUB_KEY: ${{ secrets.DAGSHUB_TOKEN }}
          # Email secrets for your send_email function
          APP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python fetch/fetch_data.py
          python features/feature_engineering.py
          python predict.py  --from-registry

