name: Retrain Model
on:
  schedule:
    # 22:00 UTC is 10 PM. Note: GitHub Actions uses UTC.
    - cron: '0 22 * * 0'
  workflow_dispatch: # Allows manual triggering

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      

      - name: Reproduce Pipeline
        env:
          DAGSHUB_KEY : ${{ secrets.DAGSHUB_TOKEN }}
          APP_PASSWORD : ${{ secrets.EMAIL_PASSWORD }}
        run: | 
          dvc repro

      